### ISSUE TITLE
Peer Review #1 - Repository

### ISSUE THREAD

**Issue by lisaoude** [sanneduinkerx/Movie-Guessr#1]
### General
- Very nice that you've added an about description!
- You could add something here about what you used to build this app, like Socket.io! 😄 
- You've added your live link! 🔥 
- Nice use of your gitignore file to hide your package-lock, node_modules and DS_Store files! 
- The name in the LICENSE file isn't your own yet!

### Readme
- There's a nice structure to your readme! 😄👍🏼 
- Concept has been described in a clear, visual way!
- Sadly you haven't implemented an API yet 😢 
- You could add a section about real-time events to your readme!
- Nice installation notes were added ✔️ 
- It might be nice to change your next steps / to do list into a wishlist and split this up using the MoSCoW method!
- Data flow looks good! It is a bit hard to read however, so a point to add to your wishlist as a could have 😝 
- You could add your LICENSE to your readme as well and link this to your LICENSE file. 😄👍🏼 

---

## To Fix This Issue
- [x] Add what you used to build your app to your about section
- [x] Add your own name to your LICENSE file
- [x] Implement an API
- [x] Describe what you do with this API
- [x] Add a description about real-time events to your readme
- [x] Change to do list into wishlist and split up using the MoSCoW method
- [x] Add LICENSE to readme and link to LICENSE file

Could have:
- [ ] Make it so your data flow is a bit more readable 😝

**Comment by sanneduinkerx** [comment]
Thanks for the feedback!
