### ISSUE TITLE
Peer review - Code

### ISSUE THREAD

**Issue by victorboucher** [sanneduinkerx/Movie-Guessr#12]
Your code is looking clean, it's not a lot so far but a nice start!
Here are some things you could improve on:
- Create your router in a separate file
- Split up the different routes in separate files in a 'routes' directory
- You could do something with the name that you fill in at the start, so for example do a post request on a route, then redirect or render to another page / view and pass in the username that someone has filled in. 
- You have the 'package-lock.json' file listed in your .gitignore file, but there is no need to do this. You should just commit it to your repo since this is a good habit when working together with multiple people. It doesn't matter that much at this point. But you could just remove that line.

Good job so far! Nice start of your project, I can't wait to see the finished project and to try it out! 🚀

**Comment by sanneduinkerx** [comment]
Thanks!
