### ISSUE TITLE
Peer Review #2 - Folder structure

### ISSUE THREAD

**Issue by lisaoude** [sanneduinkerx/Movie-Guessr#13]
## Review 
- Good to see that you've put all your 'working' files inside a src folder - keep it all nice and tidy! 🧹 
- Your public folder with specific folders inside looks good too!
- Routes folder contains just what I'd expect - routes! 
- Same as above goes for the utils & views folders! Clear names 😄 

---
No need to fix anything here! Looks good 😄

**Comment by sanneduinkerx** [comment]
Thank you!
