### ISSUE TITLE
Peer Review #2 - EJS code

### ISSUE THREAD

**Issue by lisaoude** [sanneduinkerx/Movie-Guessr#14]
## Review 
- Nice use of partials in your code!
- Since you use [this bit of code](https://github.com/sanneduinkerx/Movie-Guessr/blob/1952a1905187750f5c5f1e49c58e4b4428ea2f4e/src/views/game.ejs#L10) multiple times, maybe make that into a partial as well?
- [Right here](https://github.com/sanneduinkerx/Movie-Guessr/blob/1952a1905187750f5c5f1e49c58e4b4428ea2f4e/src/views/home.ejs#L14) you've made a little typo: mminlength needs just one m! 😄 
- [Over here](https://github.com/sanneduinkerx/Movie-Guessr/blob/1952a1905187750f5c5f1e49c58e4b4428ea2f4e/src/views/home.ejs#L21) I'd recommend adding an alt text 😄 
- It might be nice to add some extra text explaining what went wrong and/or guiding the user back to the homepage with a button [on your error page](https://github.com/sanneduinkerx/Movie-Guessr/blob/1952a1905187750f5c5f1e49c58e4b4428ea2f4e/src/views/error.ejs#L9)

---

## To Fix This Issue
- [x] Make your 'logo' into a partial
- [x] Fix typo in mminlength
- [x] Add an alt text to the home image
- [x] Handle error a bit better

**Comment by sanneduinkerx** [comment]
thanks!
