### ISSUE TITLE
Peer review - Code

### ISSUE THREAD

**Issue by victorboucher** [sanneduinkerx/Movie-Guessr#15]
Nice progress compared to previous week! You've dealt with styling and your app looks visually very nice now, good job!
Here are some code improvements:
- In your server.js file you have the randomSortedMovieData function, this function fetches the API and sorts the results of this fetch randomly and then returns it. That should work perfectly but I think the list changes every time a new user connects since you call this function every time a new user connects. You could solve this to just store this list in a variable outside of the socket logic. So once the server starts it generates the list and it will stay the same.

Everything else is looking clean, you are missing the logic that makes the guessing work, but I think once you finish that it will be a lot of fun to play! 🎉

**Comment by sanneduinkerx** [comment]
Thanks! I fixed it and put the list outside of the socket logic 😊
