### ISSUE TITLE
Peer Review #2 - CSS Code

### ISSUE THREAD

**Issue by lisaoude** [sanneduinkerx/Movie-Guessr#18]
## Review
- Your code looks really clean! 😄
- [Over here](https://github.com/sanneduinkerx/Movie-Guessr/blob/1952a1905187750f5c5f1e49c58e4b4428ea2f4e/src/public/css/style.css#L98-L103) you have an extra line of empty space at the top and bottom of your code
- Same goes for [over here](https://github.com/sanneduinkerx/Movie-Guessr/blob/1952a1905187750f5c5f1e49c58e4b4428ea2f4e/src/public/css/style.css#L234-L239), except here it's just at the bottom
- That's all I could find to fix here! 😄 

---

## To Fix This Issue
- [x] Fix extra lines of empty space

**Comment by sanneduinkerx** [comment]
thanks!
