### ISSUE TITLE
Peer Review #1 - Concept

### ISSUE THREAD

**Issue by lisaoude** [sanneduinkerx/Movie-Guessr#2]
## Review
- Your concept is very clear! 🔥 
- Just because I love my languages: I wouldn't start a new sentence with 'and', but use a comma instead 😄 
- Other concepts are described in a clear way as well 😄👍🏼 
- I really like that you let users put their display name in before really entering the app! 🔥 
- Sadly I can't see my display name once I start typing in the chat 😢 
- Chat definitely works tho! ✔️ 

---

## To Fix This Issue
- [x] Maybe change your sentence structure a little
- [x] Show users' display name in the chat as well

**Comment by sanneduinkerx** [comment]
Thank you! Fixed it :D
