### ISSUE TITLE
Peer Review #1 - API

### ISSUE THREAD

**Issue by lisaoude** [sanneduinkerx/Movie-Guessr#5]
## Review
- You haven't implemented an API or described which API you'll use yet, so I can't tell what data it offers 😢 
- Therefore there also isn't a description for getting a key & connecting to the API 😭 

---

## To Fix This Issue
- [ ] Implement an API
- [ ] Describe what data you can get from the API
- [ ] Describe what data you **use** from the API
- [ ] Describe how to get a key for this API
- [ ] Describe how to connect to this API

**Comment by sanneduinkerx** [comment]
Thank you for the feedback! I now added this 😊
