### ISSUE TITLE
Peer review - Repository

### ISSUE THREAD

**Issue by victorboucher** [sanneduinkerx/Movie-Guessr#6]
Your repo is looking very nice! You have already updated the about section with a short description and your live version. And the readme is looking good! Here are some improvements:
- I (almost) always get rid of the releases and packages sections in the about section on the right of your readme/files. You can do this by editing the about section and unchecking those checkboxes. These seem unnecessary to me since there wont be any information in those sections.
- You have not chosen/documented an API yet, so you should add that!
- You have your live link listed in the about section, but not yet in your readme. Since you already have the website live you could add it here aswell!
- Good job on making the data flow already! I'm not sure what improvements could be made here but I think it looks quite good already!

**Comment by sanneduinkerx** [comment]
Thank you! Fixed it :)
