### ISSUE TITLE
Peer Review #1 - Code 

### ISSUE THREAD

**Issue by lisaoude** [sanneduinkerx/Movie-Guessr#7]
#### Server side
- Looks pretty good overall! ✔️ 
- You've added very clear comments, which shows me that you understand what you're doing! 💬😄 
- Your ```routes.js``` file is still empty, I would remove it for now and create it again once you actually need it 😄 

#### Client side
- Once again, clear comments here! 💬🔥 

### EJS
- Looks very clean! ✔️ 
- Nice use of partials too, you can also add your header and footer here in the future 😄 

### CSS
- Nice use of comments here to create a structure within your css file 😄 
- Looks good overall! Keep it up 🔥 

---

## To Fix This Issue
- [ ] Remove ```routes.js``` file until you need it

**Comment by sanneduinkerx** [comment]
Thank you for the feedback!
