### ISSUE TITLE
Peer review - Concept

### ISSUE THREAD

**Issue by victorboucher** [sanneduinkerx/Movie-Guessr#8]
Very nice concept! I think its very cool that users have different roles during the game. You've explained your concept very well, I would not really have any questions about it after reading your readme. The chat in your live version works, but the name displaying does not yet work, and you have not created the logic for the movie guessing yet. This is all completely fine since we are only working on this for about one week! 🎉

**Comment by sanneduinkerx** [comment]
Thanks!
